-- ===== Arda missions judge bundle for oai_qrh_bridge (appended by telperion/scripts/judge_materialize.sh) =====
-- DO NOT EDIT BY HAND: generated by telperion.missions.judge. One lib holding the bridge
-- modules; they import the island's artifact and AxiomGuard modules, which the
-- island's own stanza (appended by the recipe) already builds.
lean_lib MissionChallenges where
  roots := #[`MissionChallenges]
  globs := #[.andSubmodules `MissionChallenges]
