-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_dbn_real_zeros_nine_thirtyseconds; sha256 9f188dfb076a6cf9
import Statements.RHDefs

theorem dbn_real_zeros_of_qrh_unconditional :
    ∀ t : ℝ, 9 / 32 ≤ t → ∀ z : ℂ, DBN.H t z = 0 → z.im = 0 := by sorry
