-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_dbn_real_zeros_of_qrh; sha256 e941cb9e6fa30eee
import Statements.RHDefs

theorem dbn_real_zeros_of_qrh
    (hqrh : ∀ s : ℂ, (7 / 8 : ℝ) < s.re → riemannZeta s ≠ 0) :
    ∀ t : ℝ, 9 / 32 ≤ t → ∀ z : ℂ, DBN.H t z = 0 → z.im = 0 := by sorry
