-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_dbn_real_zeros_of_zeta_halfplane; sha256 1ddb18859ce9e8ae
import Statements.RHDefs

theorem dbn_real_zeros_of_zeta_halfplane (θ : ℝ)
    (hfree : ∀ s : ℂ, θ < s.re → riemannZeta s ≠ 0) :
    ∀ t : ℝ, 2 * (θ - 1 / 2) ^ 2 ≤ t → ∀ z : ℂ, DBN.H t z = 0 → z.im = 0 := by sorry
