-- DO NOT EDIT BY HAND — generated by telperion mission; node RH_zeta_zero_free_seven_eighths; sha256 d4f9b007b50f4b46
import Statements.RHDefs

theorem qrh_seven_eighths : ∀ s : ℂ, (7 / 8 : ℝ) < s.re → riemannZeta s ≠ 0 := by sorry
