/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node rh/RH_dbn_real_zeros_nine_thirtyseconds.
   The TYPE below is the registered statement, missions/rh/lean/Statements/
   RH_dbn_real_zeros_nine_thirtyseconds.lean (header sha256 9f188dfb076a6cf9), binders and conclusion verbatim; the
   PROOF is the artifact constant `dbn_real_zeros_of_qrh_unconditional` from ArdaDBNUnconditional. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   This island is MATERIALIZED: its workspace is a foreign root package that the
   island's recipe checks out at a pinned commit, plus the island's own modules. The
   AxiomGuard imports load every island module, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here; root-package modules outside their
   import closure are not loaded. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import ArdaDBNUnconditional
import AxiomGuardDBNUnconditional
import AxiomGuardQRHBridge

theorem MissionJudge.RH_dbn_real_zeros_nine_thirtyseconds :
    ∀ t : ℝ, 9 / 32 ≤ t → ∀ z : ℂ, DBN.H t z = 0 → z.im = 0 :=
  dbn_real_zeros_of_qrh_unconditional
