/- DO NOT EDIT BY HAND -- generated by telperion.missions.judge.
   Comparator CHALLENGE for registry node rh/RH_zeta_zero_free_seven_eighths.
   The TYPE below is the registered statement, missions/rh/lean/Statements/
   RH_zeta_zero_free_seven_eighths.lean (header sha256 d4f9b007b50f4b46), binders and conclusion verbatim; the
   PROOF is the artifact constant `qrh_seven_eighths` from ArdaQRHBridge. Both kernels
   accept this module only if the artifact proves exactly the registered proposition.
   This island is MATERIALIZED: its workspace is a foreign root package that the
   island's recipe checks out at a pinned commit, plus the island's own modules. The
   AxiomGuard imports load every island module, so a vocabulary constant shadowed by
   the artifact is a duplicate declaration here; root-package modules outside their
   import closure are not loaded. The
   `namespace` and the `open` lines inside it are the artifact's own at its
   declaration, so every name in the statement resolves exactly as it does there. -/
import ArdaQRHBridge
import AxiomGuardDBNUnconditional
import AxiomGuardQRHBridge

theorem MissionJudge.RH_zeta_zero_free_seven_eighths :
    ∀ s : ℂ, (7 / 8 : ℝ) < s.re → riemannZeta s ≠ 0 :=
  qrh_seven_eighths
